version: 0.1
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Build started"
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Pipeline success"